/*
 * taskjuggler-lsp - Language Server Protocol implementation for TaskJuggler v3
 * Copyright (C) 2026  Devrin Talen <dct23@cornell.edu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/** @file */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <time.h>

/*
 * Positions / Ranges
 *
 * Both types are zero-indexed, matching the LSP specification.
 *
 * Example: the identifier "spec" in the source line (line 2):
 *
 *   task spec "Specification" {
 *   0123456789
 *
 *   LspPos start = { .line = 2, .character = 5 };
 *   LspPos end   = { .line = 2, .character = 9 };
 *   LspRange r   = { .start = start, .end = end };
 */

/** Zero-indexed source position (LSP Position). */
typedef struct {
    uint32_t line;       /**< zero-indexed line number */
    uint32_t character;  /**< zero-indexed UTF-16 code-unit offset within the line */
} LspPos;

/** Half-open source range (LSP Range). */
typedef struct {
    LspPos start;        /**< inclusive start position */
    LspPos end;          /**< exclusive end position */
} LspRange;

/** Bison's end-of-input marker (always 0). */
#define TK_EOF 0

/**
 * Lexer token value passed between bison grammar rules via the %union yylval.
 *
 * TK_* constants are defined in grammar.tab.h (generated by bison) as the
 * yytokentype enum.  Files that compare token kinds must include grammar.tab.h
 * in addition to this header.
 *
 * TK_EOF is bison's EOF marker (always 0) and is not declared in grammar.y.
 *
 * Token is used only for values passed between bison grammar rules via the
 * %union yylval mechanism.  It is not the persistent token store; that is
 * TokenSpan.
 */
typedef struct {
    int    kind;         /**< one of the TK_* / KW_* values from grammar.tab.h */
    LspPos start;        /**< source position of the first character */
    LspPos end;          /**< source position one past the last character */
    char  *text;         /**< heap-allocated; caller must free */
} Token;

/**
 * Free the heap-allocated text inside a Token (does not free the Token
 * itself).
 *
 * @param t  Token whose `text` field should be released and nulled out.
 */
void token_free(Token *t);


/* ── Slab reference types ────────────────────────────────────────────────── *
 *
 * All intra-slab references use plain integer types (no pointers) so that a
 * raw memcpy of a slab's backing arrays produces a valid, self-consistent
 * copy without any pointer-fixup pass.
 *
 *   tj_idx  — index into a flat node array; -1 == NULL
 *   str_off — byte offset into a string pool; 0 == NULL/empty
 *             (offset 0 is reserved; all stored strings begin at offset >= 1)
 */
typedef int32_t  tj_idx;
typedef uint32_t str_off;


/* ── Build-time types (INTERNAL — used only by parser.c and grammar.y) ─── *
 *
 * These pointer-based types are used only during the yyparse() build phase.
 * After parse, parse_slab_compact() converts them into slab-compatible flat
 * arrays.  Handler code must never reference tj_build_node directly.
 */

typedef struct tj_build_node tj_build_node;

/** Direction of a dependency reference. */
typedef enum {
    DEP_KIND_DEPENDS,   /**< `depends <ref>` — this task waits for ref */
    DEP_KIND_PRECEDES   /**< `precedes <ref>` — ref waits for this task */
} DepKind;

typedef struct {
    DepKind          kind;
    int              bang_count;
    char            *path;
    LspRange         source_range;
    tj_build_node   *resolved_target;   /**< always NULL in the build phase */
} dep_build;

typedef struct {
    int             token_kind;
    LspPos          start;
    LspPos          end;
    char           *text;               /**< heap-allocated strdup of yytext */
    tj_build_node  *owner;              /**< set by assign_token_owners_build() */
} tok_span_build;

struct tj_build_node {
    int              keyword;
    char            *id;
    char            *name;
    LspRange         range;
    LspRange         selection_range;
    time_t           start_date;
    time_t           end_date;
    int              has_start;
    int              has_end;
    dep_build       *dependencies;
    int              num_dependencies;
    int              dependencies_cap;
    tj_build_node   *parent_node;
    tj_build_node   *parent_doc;
    tj_build_node  **children;
    int              num_children;
    int              children_cap;
};

/**
 * Recursively free a tj_build_node subtree.
 * @param n  Root of the subtree to free.  Safe to call with NULL.
 */
void tj_build_node_free(tj_build_node *n);

/**
 * Append @p child as a child of @p parent, growing the children array.
 */
void tj_build_node_append_child(tj_build_node *parent, tj_build_node *child);

/**
 * Append a dependency onto @p task's dependencies array.
 */
void tj_build_node_push_dep(tj_build_node *task, dep_build dep);


/* ── Slab-compatible node types (PUBLIC API used by all handlers) ─────── */

/**
 * One captured `depends`/`precedes` reference stored in the parse slab.
 *
 * `path_off` is an offset into the owning parse_slab's string pool.
 * `resolved_idx` is always -1 in the parse slab; project_slab carries its own
 * resolution state in ProjectDep.
 */
typedef struct {
    DepKind   kind;
    int       bang_count;
    str_off   path_off;              /**< offset into parse_slab.strings */
    LspRange  source_range;
    tj_idx    resolved_idx;          /**< always -1 in parse_slab */
} Dependency;

/**
 * A lexical token with its source location, stored in the parse slab.
 *
 * `text_off` is an offset into the owning parse_slab's string pool; 0 means
 * the text was not captured.  `owner_idx` is the index of the innermost
 * enclosing tj_node, or -1 when the token sits outside every declaration.
 */
typedef struct {
    int       token_kind;
    LspPos    start;
    LspPos    end;
    str_off   text_off;              /**< offset into parse_slab.strings; 0 = none */
    tj_idx    owner_idx;             /**< index into parse_slab.nodes; -1 = no owner */
} TokenSpan;

/**
 * One named TaskJuggler declaration in the parse slab.
 *
 * All string fields are offsets into the owning parse_slab's string pool;
 * 0 means NULL/absent.  All node references are indices into parse_slab.nodes;
 * -1 means NULL/absent.
 *
 * children_start / dep_start are the first index into the shared children[]
 * and deps[] arrays; use num_children / num_dependencies to bound the range.
 * Both are -1 when the count is 0.
 */
typedef struct {
    int        keyword;

    str_off    id_off;
    str_off    name_off;

    LspRange   range;
    LspRange   selection_range;

    time_t     start_date;
    time_t     end_date;
    int        has_start;
    int        has_end;

    tj_idx     dep_start;            /**< first index in parse_slab.deps[]; -1 if none */
    int        num_dependencies;

    tj_idx     children_start;       /**< first index in parse_slab.children[]; -1 if none */
    int        num_children;

    tj_idx     parent_node;          /**< -1 for the synthetic root */
    tj_idx     parent_doc;           /**< -1 when not a top-level entry */
} tj_node;


/**
 * One entry per `include` directive seen in the source.  All strings are
 * heap-allocated and owned by the parse_slab that holds the IncludeRef.
 */
typedef struct {
    char *filename;
    char *task_prefix;
    char *resource_prefix;
    char *account_prefix;
    char *report_prefix;
} IncludeRef;

/**
 * The complete output of a single parse() call for one document.
 *
 * All flat arrays (nodes, children, deps, tok_spans, strings) are
 * separately heap-allocated at Phase 1; Phase 2 will pack them into a
 * single mmap-backed page.  All arrays are owned by this struct and freed
 * by parse_slab_free().
 *
 * root_idx is the index of the synthetic root node (keyword == 0).
 */
typedef struct {
    tj_node    *nodes;
    int         num_nodes;

    tj_idx     *children;            /**< flat children-index array, shared by all nodes */
    int         num_children_entries;

    Dependency *deps;                /**< flat dependency array, shared by all nodes */
    int         num_deps;

    TokenSpan  *tok_spans;
    int         num_tok_spans;
    int         num_sem_entries;     /**< upper bound on semantic-token entries */

    char       *strings;             /**< NUL-separated string pool; offset 0 reserved */
    size_t      strings_size;

    tj_idx      root_idx;            /**< index of the synthetic root node */

    IncludeRef *includes;
    int         num_includes;
} parse_slab;

/* ── Slab accessor inlines ───────────────────────────────────────────────── */

/**
 * Return a pointer to node @p i in @p s, or NULL when @p i == -1.
 */
static inline tj_node *slab_node(const parse_slab *s, tj_idx i) {
    return (i >= 0 && i < s->num_nodes) ? &s->nodes[i] : NULL;
}

/**
 * Return a pointer to the first element of @p n's children range in @p s's
 * flat children array, or NULL when @p n has no children.
 */
static inline tj_idx *slab_children(const parse_slab *s, const tj_node *n) {
    return (n && n->children_start >= 0) ? &s->children[n->children_start] : NULL;
}

/**
 * Return a pointer to the first Dependency in @p n's dep range in @p s's
 * flat deps array, or NULL when @p n has no dependencies.
 */
static inline Dependency *slab_deps(const parse_slab *s, const tj_node *n) {
    return (n && n->dep_start >= 0) ? &s->deps[n->dep_start] : NULL;
}

/**
 * Return the string at offset @p off in @p s's string pool, or NULL when
 * @p off is 0.
 */
static inline const char *slab_str(const parse_slab *s, str_off off) {
    return (off == 0) ? NULL : &s->strings[off];
}

/* ── Public API ──────────────────────────────────────────────────────────── */

/**
 * Parse @p src into a parse_slab.  Single entry point for the lexer +
 * grammar pipeline.
 *
 * @param src  NUL-terminated TaskJuggler source text.
 * @return Heap-allocated parse_slab.  Free with parse_slab_free().
 */
parse_slab *parse(const char *src);

/**
 * Release every dynamic allocation owned by @p slab and free @p slab itself.
 * Safe to call with @p slab == NULL.
 *
 * @param slab  parse_slab to free.
 */
void parse_slab_free(parse_slab *slab);

/**
 * Append an `include` directive entry from the grammar's build context.
 * Called from grammar.y; accesses the parser-internal global build context.
 *
 * @param quoted_text     Raw `include` argument (surrounding quotes stripped).
 * @param task_prefix     Value of `taskprefix` attribute, or NULL.
 * @param resource_prefix Value of `resourceprefix` attribute, or NULL.
 * @param account_prefix  Value of `accountprefix` attribute, or NULL.
 * @param report_prefix   Value of `reportprefix` attribute, or NULL.
 */
void push_include_to_build(const char *quoted_text,
                           const char *task_prefix,
                           const char *resource_prefix,
                           const char *account_prefix,
                           const char *report_prefix);

/**
 * Parse a `YYYY-MM-DD` date prefix from a TaskJuggler `TK_DATE` token's
 * text into a UTC `time_t`.  Trailing time and timezone components are
 * accepted but ignored.
 *
 * @param text  NUL-terminated token text.  May be NULL.
 * @param out   Receives the parsed time_t on success.
 * @return 1 on success, 0 if @p text does not start with a valid date.
 */
int parse_tjp_date(const char *text, time_t *out);

/**
 * Compare two positions in source order.
 *
 * @param a  Left-hand position.
 * @param b  Right-hand position.
 * @return -1 if @p a precedes @p b, 1 if @p a follows @p b, 0 if equal.
 */
static inline int pos_cmp(LspPos a, LspPos b) {
    if (a.line != b.line) return (a.line < b.line) ? -1 : 1;
    if (a.character != b.character) return (a.character < b.character) ? -1 : 1;
    return 0;
}
