/*
 * taskjuggler-lsp - Language Server Protocol implementation for TaskJuggler v3
 * Copyright (C) 2026  Devrin Talen <dct23@cornell.edu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

/* ── Positions / Ranges ──────────────────────────────────────────────────── */

typedef struct { uint32_t line, character; } LspPos;
typedef struct { LspPos start, end; } LspRange;

/* ── Token ───────────────────────────────────────────────────────────────── *
 *
 * TK_* constants are defined in grammar.tab.h (generated by bison) as the
 * yytokentype enum.  Files that compare token kinds must include grammar.tab.h
 * in addition to this header.
 *
 * TK_EOF is bison's EOF marker (always 0) and is not declared in grammar.y.
 */
#define TK_EOF 0

typedef struct {
    int    kind;  /* one of the TK_* / KW_* values from grammar.tab.h */
    LspPos start, end;
    char  *text;  /* heap-allocated; caller must free */
} Token;

void token_free(Token *t);

/* ── Symbol kinds (LSP SymbolKind values) ────────────────────────────────── */

#define SK_MODULE   2
#define SK_FUNCTION 12
#define SK_VARIABLE 13
#define SK_OBJECT   19
#define SK_EVENT    24

/* ── Symbol ──────────────────────────────────────────────────────────────── */

typedef struct Symbol Symbol;
struct Symbol {
    char    *name;           /* display name, heap-allocated */
    char    *detail;         /* TJP identifier, heap-allocated */
    int      kind;           /* SK_* constant */
    LspRange range;
    LspRange selection_range;
    Symbol  *children;       /* dynamic array */
    int      num_children;
    int      children_cap;
};

/* ── Diagnostic severity ─────────────────────────────────────────────────── */

#define DIAG_ERROR   1
#define DIAG_WARNING 2

/* ── Diagnostic ──────────────────────────────────────────────────────────── */

typedef struct {
    LspRange range;
    int       severity;
    char     *message; /* heap-allocated */
} Diagnostic;

/* ── SemToken ────────────────────────────────────────────────────────────── *
 *
 * Unified token record used for all post-parse processing (hover, completion,
 * signature help, dependency validation, semantic highlighting).
 *
 * Populated by the lexer for every token that callers may need to inspect:
 *   - All KW_* keyword tokens (including TK_DATE, TK_DURATION, TK_STR, …)
 *   - TK_IDENT, TK_LBRACE, TK_RBRACE, TK_BANG, TK_DOT, TK_COMMA
 *   - TK_LINE_COMMENT, TK_BLOCK_COMMENT
 *
 * token_kind holds the raw TK_* / KW_* constant from grammar.tab.h.
 * text is heap-allocated (strdup of yytext); NULL only for tokens where
 * the text is never needed (e.g. comments).  Caller must not modify it;
 * parse_result_free() frees it.
 */
typedef struct {
    int    token_kind;
    LspPos start, end;
    char  *text;   /* heap-allocated; may be NULL */
} SemToken;

/* ── ParseResult ─────────────────────────────────────────────────────────── */

typedef struct {
    Diagnostic  *diagnostics;
    int          num_diagnostics;
    int          diag_cap;
    Symbol      *symbols;
    int          num_symbols;
    int          sym_cap;
    SemToken    *sem_tokens;
    int          num_sem_tokens;
    int          sem_tok_cap;
} ParseResult;

/* ── Public API ──────────────────────────────────────────────────────────── */

ParseResult parse(const char *src);
void        parse_result_free(ParseResult *r);
void        symbol_free(Symbol *s);

/* Compare two positions. Returns -1, 0, or 1. */
static inline int pos_cmp(LspPos a, LspPos b) {
    if (a.line != b.line) return (a.line < b.line) ? -1 : 1;
    if (a.character != b.character) return (a.character < b.character) ? -1 : 1;
    return 0;
}
