/*
 * taskjuggler-lsp - Language Server Protocol implementation for TaskJuggler v3
 * Copyright (C) 2026  Devrin Talen <dct23@cornell.edu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/** @file */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <time.h>

#include "arena.h"

/*
 * Positions / Ranges
 *
 * Both types are zero-indexed, matching the LSP specification.
 *
 * Example: the identifier "spec" in the source line (line 2):
 *
 *   task spec "Specification" {
 *   0123456789
 *
 *   LspPos start = { .line = 2, .character = 5 };
 *   LspPos end   = { .line = 2, .character = 9 };
 *   LspRange r   = { .start = start, .end = end };
 */

/** Zero-indexed source position (LSP Position). */
typedef struct {
    uint32_t line;       /**< zero-indexed line number */
    uint32_t character;  /**< zero-indexed UTF-16 code-unit offset within the line */
} LspPos;

/** Half-open source range (LSP Range). */
typedef struct {
    LspPos start;        /**< inclusive start position */
    LspPos end;          /**< exclusive end position */
} LspRange;

/** Bison's end-of-input marker (always 0). */
#define TK_EOF 0

/**
 * Lexer token value passed between bison grammar rules via the %union yylval.
 *
 * TK_* constants are defined in grammar.tab.h (generated by bison) as the
 * yytokentype enum.  Files that compare token kinds must include grammar.tab.h
 * in addition to this header.
 *
 * TK_EOF is bison's EOF marker (always 0) and is not declared in grammar.y.
 *
 * Token is used only for values passed between bison grammar rules via the
 * %union yylval mechanism.  It is not the persistent token store; that is
 * TokenSpan.
 */
typedef struct {
    int    kind;         /**< one of the TK_* / KW_* values from grammar.tab.h */
    LspPos start;        /**< source position of the first character */
    LspPos end;          /**< source position one past the last character */
    char  *text;         /**< borrowed pointer into the parse's token arena
                          *   (interned by g_push_tok_span), or NULL.  Never
                          *   freed via the token; strdup it to keep it. */
} Token;

/**
 * Drop a Token's borrowed lexeme pointer (sets `text` to NULL).  The text is
 * arena-owned (see Token.text), so nothing is freed here; this only exists so
 * grammar discard paths and the bison destructor have a uniform call.
 *
 * @param t  Token whose `text` field should be nulled out.
 */
void token_free(Token *t);


/* ── tj_node ─────────────────────────────────────────────────────────────── *
 *
 * Generic node type representing a named TaskJuggler declaration:
 * task, account, resource (and shift), report (and related report-type
 * declarations), or project.  The node kind is encoded by the `keyword`
 * field — a raw KW_* / TK_* constant from grammar.tab.h.
 *
 * Memory ownership: Documents own every tj_node they parse.  When this
 * Document is freed, the entire owned subtree is freed.  Per-Document
 * tj_node trees are immutable after parse — cross-Document hoisting
 * lives in a wholly separate global tree built by server.c, not on
 * these nodes.
 */
typedef struct tj_node tj_node;

/** Direction of a dependency reference. */
typedef enum {
    DEP_KIND_DEPENDS,   /**< `depends <ref>` — this task waits for ref */
    DEP_KIND_PRECEDES   /**< `precedes <ref>` — ref waits for this task */
} DepKind;

/**
 * One captured `depends`/`precedes` reference on a task tj_node.
 *
 * Populated by the grammar action for `dep_ref` at parse time.  These
 * per-document references are left unresolved here; cross-file
 * resolution runs against the assembled per-Project ProjectNode tree
 * and is memoized there (ProjectDep.resolved, see project_tree.h).
 *
 * Memory ownership: the enclosing tj_node owns the `dependencies` array;
 * `path` borrows the parse's token arena (built by the dep_path rule) and
 * is reclaimed in bulk with it, never freed per dependency.
 */
typedef struct Dependency {
    DepKind   kind;             /**< whether this dep is `depends` or `precedes` */
    int       bang_count;       /**< number of leading `!` characters */
    char     *path;             /**< dotted identifier path; borrowed from the token arena */
    LspRange  source_range;     /**< spans the bang(s) + dotted path in source */
} Dependency;

/**
 * One named declaration in a parsed document: a task, account,
 * resource (or shift), report (or related report-kind), or project.
 * The node kind is identified by the raw `keyword` field, which
 * holds the KW_/TK_ constant the grammar matched.  Generic enough
 * to back document-symbol, completion, definition, references,
 * folding, and dependency resolution — handlers branch on `keyword`
 * when they need to distinguish kinds.
 *
 * Memory: `dependencies`, `children`, and every transitively reachable
 * child node are owned by the tj_node and freed by tj_node_free().
 * `id` and `name` instead borrow the parse's token arena (which outlives
 * the tree within the same doc_snapshot), so they are not freed per node.
 * The cross-tree `parent_node` pointer is borrowed and never freed here.
 */
struct tj_node {
    /* ── Identity ── */
    int        keyword;        /**< KW_ / TK_ constant from grammar.tab.h; 0 for synthetic per-doc roots */
    char      *id;              /**< TJP identifier; borrowed from the token arena, NULL on synthetic roots */
    char      *name;            /**< display name; borrowed from the token arena, NULL on synthetic roots */

    /* ── Source location ── */
    LspRange   range;           /**< full declaration including body */
    LspRange   selection_range; /**< just the identifier (or keyword) token */

    /* ── Task-only attributes (zero on other kinds) ── */
    time_t     start_date;      /**< explicit `start` date, valid if has_start */
    time_t     end_date;        /**< explicit `end` date, valid if has_end */
    int        has_start;       /**< 1 when start_date is populated */
    int        has_end;         /**< 1 when end_date is populated */

    /* ── Task-only dependencies (zero on other kinds) ──
     *
     * Captured at parse time from `depends` / `precedes` attributes,
     * one entry per dep_ref in source order.  Empty on tasks that
     * declare no dependencies and on every non-task node.  Owned by
     * this node; freed by tj_node_free(). */
    Dependency *dependencies;     /**< owned array; @see num_dependencies */
    int         num_dependencies; /**< number of valid entries in `dependencies` */
    int         dependencies_cap; /**< allocated capacity of `dependencies` */

    /* ── Tree links ──
     *
     * parent_node    — semantic parent in the global tree.  May cross
     *                  document boundaries: when this Document is
     *                  included with a taskprefix, top-level tasks of
     *                  this Document point at the prefix-target node
     *                  in the includer's Document.  In-document
     *                  parents stay within the same Document.
     *                  NULL on the document's synthetic root.
     *
     * children       — locally declared children in source order.
     *                  Owned by this node; freed by tj_node_free().
     */
    tj_node   *parent_node;  /**< borrowed; see comment above */
    tj_node  **children;     /**< owned array; @see num_children */
    int        num_children; /**< number of valid entries in `children` */
    int        children_cap; /**< allocated capacity of `children` */
};

/**
 * Recursively free a tj_node subtree.  Frees the node's own strings, its
 * children (recursively, via the owned `children` array), and the node
 * itself.  Does NOT walk `parent_node` upward.
 *
 * @param n  Root of the subtree to free.  Safe to call with NULL.
 */
void tj_node_free(tj_node *n);

/**
 * Append @p child as a locally declared child of @p parent (growing the
 * `children` array as needed) and set @p child's `parent_node` to @p parent.
 *
 * @param parent  Owning node.
 * @param child   Child to attach (transfer of ownership).
 */
void tj_node_append_child(tj_node *parent, tj_node *child);

/**
 * Append a captured dependency reference onto @p task's `dependencies`
 * array, growing it as needed.  Takes ownership of @p dep.path.
 * `resolved_target` is initialized to NULL.
 *
 * @param task  Task tj_node (caller guarantees keyword == KW_TASK).
 * @param dep   Source-position-bearing Dependency whose `path` is heap-owned.
 */
void tj_node_push_dependency(tj_node *task, Dependency dep);

/** Forward declaration; the full struct is defined in diagnostics.h. */
typedef struct Diagnostic Diagnostic;

/**
 * A lexical token with its source location.
 *
 * Used as a flat, ordered sequence for all cursor-position queries: hover,
 * completion, signature help, semantic highlighting, folding ranges, etc.
 *
 * Populated by the lexer for every token that callers may need to inspect:
 *   - All KW_* keyword tokens (including TK_DATE, TK_DURATION, TK_STR, …)
 *   - TK_IDENT, TK_LBRACE, TK_RBRACE, TK_BANG, TK_DOT, TK_COMMA
 *   - TK_LINE_COMMENT, TK_BLOCK_COMMENT
 *
 * `token_kind` holds the raw TK_* / KW_* constant from grammar.tab.h.
 * `text` points into the owning ParseOutput / doc_snapshot's token arena
 * (a NUL-terminated copy of yytext); NULL only for tokens where the text is
 * never needed.  Caller must not modify or free it; it is released in bulk
 * when the arena is freed.
 *
 * `owner` points to the innermost enclosing tj_node in this same
 * document's per-kind tree (whichever tree the enclosing declaration
 * lives in).  NULL when the token sits outside every declaration.
 */
typedef struct {
    int       token_kind;   /**< raw TK_/KW_ constant from grammar.tab.h */
    LspPos    start;        /**< inclusive start position in the source */
    LspPos    end;          /**< exclusive end position in the source */
    char     *text;         /**< owned strdup of the lexeme; may be NULL */
    tj_node  *owner;        /**< borrowed innermost enclosing tj_node, or NULL */
} TokenSpan;

/**
 * Return a retired token-span buffer to the parser's single-entry recycle
 * cache so the next parse can reuse its already-mapped pages instead of
 * mmap-ing (and page-faulting) a fresh multi-MB block.  Called wherever a
 * ParseOutput / doc_snapshot's `tok_spans` would otherwise be free()'d.
 * Thread-safe; surplus buffers (slot already full) are freed.  NULL is a no-op.
 *
 * @param buf  The `tok_spans` buffer being retired (may be NULL).
 */
void tok_spans_release(TokenSpan *buf);

/**
 * One entry per `include` directive seen in the source.  `filename` is the
 * unquoted target as it appeared in the include statement.  The four
 * `*_prefix` fields carry the matching attribute from the include body
 * (e.g. `include "bar.tji" { taskprefix t1.t2 }` produces
 * `task_prefix = "t1.t2"`); each is NULL when the corresponding attribute
 * was not present.  All strings are heap-allocated and owned by the
 * ParseOutput / Document that holds the IncludeRef.
 */
typedef struct {
    char *filename;        /**< owned unquoted target as it appeared in the include statement */
    char *task_prefix;     /**< owned `taskprefix` argument, or NULL when not present */
    char *resource_prefix; /**< owned `resourceprefix` argument, or NULL when not present */
    char *account_prefix;  /**< owned `accountprefix` argument, or NULL when not present */
    char *report_prefix;   /**< owned `reportprefix` argument, or NULL when not present */
} IncludeRef;

/**
 * The complete output of a single parse() call for one document.
 *
 * One ParseOutput per parse — its lifetime is tied to the owning Document
 * (the server creates a fresh one on every didOpen/didChange and frees the
 * previous one).  All arrays and tj_node subtrees referenced from here are
 * owned by this struct and freed by parse_output_free().
 *
 * The synthetic `root` is always non-NULL.  Its `keyword` is 0; its
 * `children` array holds every top-level declaration of the document —
 * tasks, accounts, resources/shifts, the report family, and the project
 * block — in source order.  A `project ... { ... }` block's own body
 * declarations are hoisted to siblings under `root` (the project node
 * keeps no children); `assign_token_owners()` restores that nesting for
 * token ownership only.  The tree is immutable after parse —
 * cross-Document hoisting happens in a separately allocated global tree
 * built by server.c.
 */
typedef struct {
    tj_node   *root;         /**< synthetic root; children are all top-level declarations in source order */

    TokenSpan *tok_spans;       /**< owned flat array of every captured token */
    int        num_tok_spans;   /**< number of valid entries in `tok_spans` */
    int        num_sem_entries; /**< upper bound on semantic-token entries (one per source line covered) */
    str_arena *tok_arena;       /**< owned backing store for every `tok_spans[i].text` */

    IncludeRef *includes;       /**< owned array; one entry per `include` directive */
    int         num_includes;   /**< number of valid entries in `includes` */
    int         includes_cap;   /**< allocated capacity of `includes` */
} ParseOutput;

/* ── Public API ──────────────────────────────────────────────────────────── */

/**
 * Parse @p src into a ParseOutput.  Single entry point for the lexer +
 * grammar pipeline.
 *
 * @param src  NUL-terminated TaskJuggler source text.
 * @return Heap-allocated ParseOutput.  Free with parse_output_free().
 */
ParseOutput *parse(const char *src);

/**
 * Release every dynamic allocation owned by @p po and free @p po itself.
 * Safe to call with @p po == NULL.
 *
 * @param po  ParseOutput to free.
 */
void parse_output_free(ParseOutput *po);

/**
 * Append an `include` directive entry to @p po->includes.  The four prefix
 * pointers may be NULL (attribute not present); when non-NULL each is
 * deep-copied so the caller retains ownership of its inputs.
 *
 * @param po              ParseOutput being populated.
 * @param quoted_text     Raw `include` argument as it appears in source;
 *                        the surrounding quotes are stripped before storing.
 * @param task_prefix     Value of `taskprefix` attribute, or NULL.
 * @param resource_prefix Value of `resourceprefix` attribute, or NULL.
 * @param account_prefix  Value of `accountprefix` attribute, or NULL.
 * @param report_prefix   Value of `reportprefix` attribute, or NULL.
 */
void push_include(ParseOutput *po, const char *quoted_text,
                  const char *task_prefix,
                  const char *resource_prefix,
                  const char *account_prefix,
                  const char *report_prefix);

/**
 * Parse a `YYYY-MM-DD` date prefix from a TaskJuggler `TK_DATE` token's
 * text into a UTC `time_t`.  Trailing time and timezone components
 * (e.g. `-09:00`, `+0100`) are accepted but ignored.
 *
 * @param text  NUL-terminated token text.  May be NULL.
 * @param out   Receives the parsed time_t on success.
 * @return 1 on success, 0 if @p text does not start with a valid date.
 */
int parse_tjp_date(const char *text, time_t *out);

/**
 * Compare two positions in source order.
 *
 * @param a  Left-hand position.
 * @param b  Right-hand position.
 * @return -1 if @p a precedes @p b, 1 if @p a follows @p b, 0 if equal.
 */
static inline int pos_cmp(LspPos a, LspPos b) {
    if (a.line != b.line) return (a.line < b.line) ? -1 : 1;
    if (a.character != b.character) return (a.character < b.character) ? -1 : 1;
    return 0;
}
