name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install libcjson-dev flex bison
    - name: make
      run: make
    - name: test
      run: python lsp_test.py ./taskjuggler-lsp --all test/cases/
